# #version: "3.8"

# services:
#   client:
#     build: ./client
#     ports:
#       - "3000:80" # React via Nginx on port 80, exposed as 3000
#     depends_on:
#       - server

#   server:
#     build: ./server
#     ports:
#       - "5000:5000"
#     environment:
#       - MONGO_URL=mongodb://mongo:27017/crud
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:8.0.5
#     container_name: mongo-db
#     ports:
#       - "27018:27017"
#     volumes:
#       - mongo_data:/data/db
#     restart: always

# volumes:
#   mongo_data:
# version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://qmsUAT:India%40321@mongo:27017/crud?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.5
    container_name: mongo-db
    ports:
      - "27018:27017" # hostPort:containerPort
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=qmsUAT
      - MONGO_INITDB_ROOT_PASSWORD=India@321

volumes:
  mongo_data:
